MEDICATION_TERM_MAP = {
    "aciclovir": "Aciclovir",
    "adalimumab": "Adalimumab",
    "alendronato": "Alendronato",
    "alopurinol": "Alopurinol",
    "alprazolam": "Alprazolam",
    "amiodarona": "Amiodarona",
    "amlodipino": "Amlodipino",
    "amoxicilina": "Amoxicilina",
    "amoxicilina acido clavulanico": "Amoxicilina/Ácido clavulánico",
    "apixaban": "Apixabán",
    "atorvastatina": "Atorvastatina",
    "azatioprina": "Azatioprina",
    "beclometasona": "Beclometasona (inhalador)",
    "betametasona": "Betametasona (tópica)",
    "bisoprolol": "Bisoprolol",
    "calcipotriol": "Calcipotriol (tópico)",
    "carbamazepina": "Carbamazepina",
    "cetirizina": "Cetirizina",
    "cianocobalamina": "Cianocobalamina",
    "claritromicina": "Claritromicina",
    "clopidogrel": "Clopidogrel",
    "colchicina": "Colchicina",
    "colecalciferol": "Colecalciferol",
    "diazepam": "Diazepam",
    "domperidona": "Domperidona",
    "enalapril": "Enalapril",
    "entacapona": "Entacapona",
    "epoetina alfa": "Epoetina alfa",
    "escitalopram": "Escitalopram",
    "espironolactona": "Espironolactona",
    "fenazopiridina": "Fenazopiridina",
    "fenofibrato": "Fenofibrato",
    "finasterida": "Finasterida",
    "fluticasona": "Fluticasona (inhalador)",
    "furosemida": "Furosemida",
    "gabapentina": "Gabapentina",
    "hidroclorotiazida": "Hidroclorotiazida",
    "hidrocortisona": "Hidrocortisona (tópica)",
    "hidroxicloroquina": "Hidroxicloroquina",
    "ibuprofeno": "Ibuprofeno",
    "indapamida": "Indapamida",
    "insulina detemir": "Insulina detemir",
    "insulina glargina": "Insulina glargina",
    "insulina lispro": "Insulina lispro",
    "levetiracetam": "Levetiracetam",
    "levodopa carbidopa": "Levodopa/Carbidopa",
    "levofloxacino": "Levofloxacino",
    "levotiroxina": "Levotiroxina",
    "lisinopril": "Lisinopril",
    "loratadina": "Loratadina",
    "losartan": "Losartán",
    "losartan": "Losartán",
    "melatonina": "Melatonina",
    "mesalazina": "Mesalazina",
    "metamizol": "Metamizol",
    "metformina": "Metformina",
    "metoprolol": "Metoprolol",
    "metotrexato": "Metotrexato",
    "micofenolato mofetil": "Micofenolato mofetil",
    "montelukast": "Montelukast",
    "naproxeno": "Naproxeno",
    "nitrofurantoina": "Nitrofurantoína",
    "olopatadina": "Olopatadina (colirio)",
    "omeprazol": "Omeprazol",
    "orlistat": "Orlistat",
    "oxibutinina": "Oxibutinina",
    "paracetamol": "Paracetamol",
    "paroxetina": "Paroxetina",
    "perindopril": "Perindopril",
    "pramipexol": "Pramipexol",
    "pravastatina": "Pravastatina",
    "prednisona": "Prednisona",
    "propranolol": "Propranolol",
    "ramipril": "Ramipril",
    "roflumilast": "Roflumilast",
    "rosuvastatina": "Rosuvastatina",
    "salbutamol": "Salbutamol (inhalador)",
    "salmeterol": "Salmeterol (inhalador)",
    "sertralina": "Sertralina",
    "simvastatina": "Simvastatina",
    "sulfato ferroso": "Sulfato ferroso",
    "sumatriptan": "Sumatriptán",
    "sumatriptán": "Sumatriptán",
    "tamsulosina": "Tamsulosina",
    "testosterona enantato": "Testosterona enantato",
    "tiamazol": "Tiamazol",
    "timolol": "Timolol (colirio)",
    "tiotropio": "Tiotropio (inhalador)",
    "tramadol": "Tramadol",
    "trihexifenidilo": "Trihexifenidilo",
    "zolpidem": "Zolpidem",
    "acido acetilsalicilico": "Ácido acetilsalicílico",
}